### Default settings

# Vaadin debug mode is disabled by default
vaadin.servlet.productionMode: true

spring:
  application:
    name: Temperature Server

# Flyway DB migrations are disabled by default for in-memory H2 support
# When using other datasources, this needs to be enabled specifically
  flyway.enabled: false

# Info Endpoint
info:
  service: @project.name@
  version: @project.version@

# Postgres DB
---
spring:
  profiles: postgres
  
  # disabling feature detection - just preventing warnings and unnecessary stack traces in the logs
  jpa:
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  
  datasource:
    url: jdbc:postgresql://localhost:5432/temperature
    username: postgres
    password: postgres

  flyway:
    enabled: true
    locations: classpath:/db/migration/postgres

# MariaDB / MySql
---
spring:
  profiles: mariadb

  jpa:
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.MariaDBDialect

  datasource:
    url: jdbc:mysql://192.168.11.20:3307/temperature
    username: temperature
    password: temperature
    driver-class-name: org.mariadb.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:/db/migration/mariadb

# Local development options
---
spring:
  profiles: local

loggging.level:
  de.tfsw: DEBUG

vaadin.servlet.productionMode: false
management.endpoints.web.exposure.include: "*"
# logging.level.org.hibernate.SQL: DEBUG
